"use strict";

exports.__esModule = true;
exports.selectNotes = exports.selectNoteLabels = exports.selectNoteIds = exports.selectDrawerItems = exports.selectCurrentBoard = exports.selectColumns = exports.selectBoardColumnIds = exports.selectBoardById = exports.selectAppUiTheme = exports.selectAppModal = exports.selectAppBoardIds = void 0;
const selectApp = (state /*: StoreState */) => state.app || {};
const selectAppModal = (state /*: StoreState */) => state.modal || {};
exports.selectAppModal = selectAppModal;
const selectAppCurrentBoard = (state /*: StoreState */) => selectApp(state).boardId;
const selectAppBoardIds = (state /*: StoreState */) => selectApp(state).boardIds || [];
exports.selectAppBoardIds = selectAppBoardIds;
const selectAppUiTheme = (state /*: StoreState */) => selectApp(state).uiTheme;
exports.selectAppUiTheme = selectAppUiTheme;
const selectDrawerItems = (state /*: StoreState */) => state.drawerMsg || [];
exports.selectDrawerItems = selectDrawerItems;
const selectBoards = (state /*: StoreState */) => state.boards || {};
const selectCurrentBoard = (state /*: StoreState */) => selectBoards(state)[selectAppCurrentBoard(state)] || {};
exports.selectCurrentBoard = selectCurrentBoard;
const selectBoardById = (state /*: StoreState */, boardId /*: string */) => selectBoards(state)[boardId] || {};
exports.selectBoardById = selectBoardById;
const selectBoardColumnIds = (state /*: StoreState */, boardId /*: string */) => selectBoardById(state, boardId).columnIds || [];
exports.selectBoardColumnIds = selectBoardColumnIds;
const selectNotes = (state /*: StoreState */) => state.notes || {};
exports.selectNotes = selectNotes;
const selectNoteLabels = (state /*: StoreState */) => state.noteLabels || {};
exports.selectNoteLabels = selectNoteLabels;
const selectColumns = (state /*: StoreState */) => state.columns || {};
exports.selectColumns = selectColumns;
const selectColumn = (state /*: StoreState */, columnId /*: string */) => selectColumns(state)[columnId] || {};
const selectNoteIds = (state /*: StoreState */, columnId /*: string */) => selectColumn(state, columnId).noteIds || [];
exports.selectNoteIds = selectNoteIds;
//# sourceMappingURL=selectors.js.map